spring:
  application:
    name: ad-eureka
server:
  port: 8761
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: false #默认为false，是否以ip注册
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka-server.host:8761/eureka/
#      defaultZone: http://localhost:8761/eureka/