spring:
  application:
    name: ad-gateway
server:
  port: 8040
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server.host:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always